apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podsets.app.example.com
spec:
  group: app.example.com
  names:
    kind: PodSet
    listKind: PodSetList
    plural: podsets
    singular: podset
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PodSet is the Schema for the podsets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PodSetSpec defines the desired state of PodSet
          properties:
            namespace:
              type: string
            podsetlogger-deployment-spec:
              description: Podsetlogger contain the value necessary to make a deployment
              properties:
                imagelocation:
                  type: string
                imagename:
                  type: string
                imagepullpolicy:
                  type: string
                replicas:
                  format: int32
                  type: integer
                version:
                  type: string
              required:
              - imagelocation
              - imagename
              - imagepullpolicy
              - replicas
              - version
              type: object
            podsetlogger-service-spec:
              description: PodSetloggerService spec
              properties:
                ports:
                  description: Ports spec
                  properties:
                    port:
                      format: int32
                      type: integer
                    targetport:
                      format: int32
                      type: integer
                  required:
                  - port
                  - targetport
                  type: object
                selectors:
                  items:
                    description: Selectors spec
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - value
                    type: object
                  type: array
                servicename:
                  type: string
                servicetype:
                  description: Service Type string describes ingress methods for a
                    service
                  type: string
              required:
              - ports
              - selectors
              - servicename
              - servicetype
              type: object
            watch:
              items:
                description: Watch element
                properties:
                  name:
                    type: string
                  value:
                    type: string
                required:
                - name
                - value
                type: object
              type: array
          required:
          - namespace
          - podsetlogger-deployment-spec
          - podsetlogger-service-spec
          - watch
          type: object
        status:
          description: PodSetStatus defines the observed state of PodSet
          properties:
            currentdeployement:
              description: Deployment contain the value necessary to make a deployment
              properties:
                error:
                  type: string
                imagelocation:
                  type: string
                imagpullpolicy:
                  type: string
                name:
                  type: string
                replicas:
                  format: int32
                  type: integer
                version:
                  type: string
              required:
              - error
              - imagelocation
              - imagpullpolicy
              - name
              - replicas
              - version
              type: object
            podnames:
              items:
                type: string
              type: array
            previousdeployement:
              description: Deployment contain the value necessary to make a deployment
              properties:
                error:
                  type: string
                imagelocation:
                  type: string
                imagpullpolicy:
                  type: string
                name:
                  type: string
                replicas:
                  format: int32
                  type: integer
                version:
                  type: string
              required:
              - error
              - imagelocation
              - imagpullpolicy
              - name
              - replicas
              - version
              type: object
            watch:
              items:
                description: Watch element
                properties:
                  name:
                    type: string
                  value:
                    type: string
                required:
                - name
                - value
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
