apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podsets.app.example.com
spec:
  group: app.example.com
  names:
    kind: PodSet
    listKind: PodSetList
    plural: podsets
    singular: podset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PodSet is the Schema for the podsets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PodSetSpec defines the desired state of PodSet
          properties:
            imageLocation:
              type: string
            imagePullPolicy:
              type: string
            replicas:
              format: int32
              type: integer
            version:
              type: string
          required:
          - imageLocation
          - imagePullPolicy
          - replicas
          - version
          type: object
        status:
          description: PodSetStatus defines the observed state of PodSet
          properties:
            currentDeployement:
              description: Deployment contain the value necessary to make a deployment
              properties:
                error:
                  type: string
                imageLocation:
                  type: string
                name:
                  type: string
                pullPolicy:
                  type: string
                replicas:
                  format: int32
                  type: integer
                version:
                  type: string
              required:
              - error
              - imageLocation
              - name
              - pullPolicy
              - replicas
              - version
              type: object
            podNames:
              items:
                type: string
              type: array
            previousDeployement:
              description: Deployment contain the value necessary to make a deployment
              properties:
                error:
                  type: string
                imageLocation:
                  type: string
                name:
                  type: string
                pullPolicy:
                  type: string
                replicas:
                  format: int32
                  type: integer
                version:
                  type: string
              required:
              - error
              - imageLocation
              - name
              - pullPolicy
              - replicas
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
