kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podset-operator
subjects:
- kind: ServiceAccount
  name: podset-operator
  namespace: podset-operator-group
roleRef:
  kind: ClusterRole
  name: podset-operator
  apiGroup: rbac.authorization.k8s.io
